version: '3'

services: 

  nginx:
    build: 
      dockerfile: Dockerfile.nginx
    container_name: nginx
    networks: 
      - node-network
    tty: true
    ports: 
      - "8080:8080"
    depends_on: 
       - db
       - node

  node:
    build: 
      dockerfile: Dockerfile.node
    container_name: node
    networks: 
      - node-network
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge  